kafka:
    bootstrap-servers: 192.168.1.100:9092


###########################################################################
# Database settings
###########################################################################
app.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/mysql
    username: root
    password: Yanjiangshan2019@
    minPoolSize: 1
    maxPoolSize: 5